name: "Locize diff"
description: "Wait a designated number of milliseconds"
runs:
  using: "node12"
  main: "dist/index.js"
inputs:
  milliseconds: # id of input
    description: "number of milliseconds to wait"
    required: true
    default: "1000"
outputs:
  time: # output will be available to future steps
    description: "The message to output"
